Skip test_unix_domain_socket on darwin when non-root
Mknod() on Darwin (OX X / macOS) requires super-user privileges.

Otherwise, this test fails with:

    OSError: [Errno 1] Operation not permitted